version: '3.8'

services:
  app:
    build: .
    ports:
      - "${PORT}:${PORT}"
    environment:
      - APP_ENV=${APP_ENV}
      - PORT=${PORT}
      - PG_USERNAME=${PG_USERNAME}
      - PG_PASS=${PG_PASS}
      - PG_DB_NAME=${PG_DB_NAME}
      - PG_PORT=${PG_PORT}
      - PG_HOST=postgres
      - PG_TYPE=${PG_TYPE}
      - PG_SYNCHRONIZE=${PG_SYNCHRONIZE}
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_DB: ${PG_DB_NAME}
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
